export STORK_BRANCH=${TRAVIS_BRANCH:-}
export STORK_TAG=${TRAVIS_TAG:-}
export STORK_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-false}
export STORK_EVENT_TYPE=${TRAVIS_EVENT_TYPE}
export STORK_COMMIT=${TRAVIS_COMMIT:-head}
export STORK_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER:-0}
